In [2]:
import numpy as np
import matplotlib.pyplot as pt


In [3]:
velocidades = []

datos = open("velocidades.txt", "r")
for linea in datos:
    velocidades.append(linea)

tiempo = []
for v in velocidades:
    t = v.split('\t')
    tiempo.append(t)



In [4]:
np.polynomial.legendre.leggauss(1)

(array([0.]), array([2.]))

In [6]:
legen = []
for i in range(1,11):
    w = np.polynomial.legendre.leggauss(i)
    legen.append(w)

for l in legen:
    print(l)

(array([0.]), array([2.]))
(array([-0.57735027,  0.57735027]), array([1., 1.]))
(array([-0.77459667,  0.        ,  0.77459667]), array([0.55555556, 0.88888889, 0.55555556]))
(array([-0.86113631, -0.33998104,  0.33998104,  0.86113631]), array([0.34785485, 0.65214515, 0.65214515, 0.34785485]))
(array([-0.90617985, -0.53846931,  0.        ,  0.53846931,  0.90617985]), array([0.23692689, 0.47862867, 0.56888889, 0.47862867, 0.23692689]))
(array([-0.93246951, -0.66120939, -0.23861919,  0.23861919,  0.66120939,
        0.93246951]), array([0.17132449, 0.36076157, 0.46791393, 0.46791393, 0.36076157,
       0.17132449]))
(array([-0.94910791, -0.74153119, -0.40584515,  0.        ,  0.40584515,
        0.74153119,  0.94910791]), array([0.12948497, 0.27970539, 0.38183005, 0.41795918, 0.38183005,
       0.27970539, 0.12948497]))
(array([-0.96028986, -0.79666648, -0.52553241, -0.18343464,  0.18343464,
        0.52553241,  0.79666648,  0.96028986]), array([0.10122854, 0.22238103, 0.31370665, 0.362683

In [7]:
def trapecio(a,b,f,N):
    h = (b-a)/N
    I = h*(f(a)-f(b))/2
    I += h*sum( [f(a + k*h) for k in range(1,N)])
    return I
    

In [26]:
def simpson(a,b,f,N):
    h = (b-a)/N
    I = h*(f(a)+f(b))/3
    for i in range(1,int(N)):
        if (i%2==0):
            I += 2*f(a+i*h)*h/3
        elif (i%2==1):
            I += 4*f(a+i*h)*h/3
    return I


In [15]:
def f(x):
    return x
    
trapecio(0,2,f,10000)

1.9996

In [29]:
simpson(0,2,f,100)

2.0

In [22]:
2%2

0